import { IsNotEmpty, IsOptional, IsString } from 'class-validator';

export class CreateChatRoomDto {
  @IsString()
  @IsNotEmpty()
  adId: string;

  // Optional custom roomId; usually generated by service
  @IsOptional()
  @IsString()
  roomId?: string;
}
