import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsNotEmpty, IsString, IsOptional } from 'class-validator';

export class RegisterFcmTokenDto {
    @ApiProperty({
        description: 'The FCM token generated by the client device',
        example: 'dE1xX0..._z_Y',
        required: true,
    })
    @IsString()
    @IsNotEmpty()
    token: string;

    @ApiProperty({
        description: 'The platform of the device',
        enum: ['web', 'android', 'ios'],
        example: 'web',
        required: true,
    })
    @IsEnum(['web', 'android', 'ios'])
    @IsNotEmpty()
    platform: string;

    @ApiProperty({
        description: 'Unique ID of the device (for de-duplication)',
        example: 'android-123456789',
        required: false,
    })
    @IsString()
    @IsOptional()
    deviceId?: string;
}
