import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsOptional, IsString } from 'class-validator';

export class RegisterFcmTokenDto {
    @ApiProperty({
        description: 'The FCM token generated by the client device',
        example: 'dE1xX0..._z_Y',
        required: true,
    })
    @IsString()
    @IsNotEmpty()
    token: string;

    @ApiProperty({
        description: 'The ID of the user',
        example: 'user_123',
        required: false,
    })
    @IsString()
    @IsOptional()
    userId?: string;

    @ApiProperty({
        description: 'The device platform (e.g., ios, android, web)',
        example: 'android',
        required: false,
    })
    @IsString()
    @IsOptional()
    platform?: string;

    @ApiProperty({
        description: 'Unique identifier for the device',
        example: 'device_123',
        required: false,
    })
    @IsString()
    @IsOptional()
    deviceId?: string;
}
